---
title: "Krause, et al. (2020); https://doi.org/10.1002/csc2.20253"
author: "Matheus D Krause"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.width=13, fig.height=13)
```

```{r cars}
## loading results from server ##
res <- readRDS("./results/resultsFA.rds")

## some formatting here and there ##
res$missEnv <- as.factor(res$missEnv) 

res$model <- gsub('CS', "Compound symmetry", res$model) 

res$model <- gsub('FA2', "Factor analytic", res$model) 

res$missGeno <- gsub('0.1', "10−fold cross-validation 
                     (10% of genotypes considered as missing data within a given environment)", 
                     res$missGeno) 

res$missGeno <- gsub('0.2', "5−fold cross-validation 
                     (20% of genotypes considered as missing data within a given environment)", 
                     res$missGeno) 

res$missGeno <- gsub('0.4', 
                     "40% of genotypes considered as missing data within a given environment",
                     res$missGeno) 

res$missGeno <- as.factor(res$missGeno) 

res$missGeno<-factor(res$missGeno, levels = levels(res$missGeno)[c(1, 3, 2)])

## plotting results ##
library(ggplot2)
ggplot(res, aes(x=missEnv, y=corr, fill = model)) + 
  facet_wrap(~missGeno, nrow = 3) + 
  theme_bw() + 
  geom_boxplot() + 
  ylab("Predictive accuracy") + 
  xlab("Number of missing environments") +
  theme(legend.position = "bottom") + 
  guides(fill=guide_legend(title= "Models"))
```
